name: Secrets
description: "A Buildkite plugin to fetch secrets from Buildkite secrets"
author: "@buildkite-plugins"
requirements:
  - bash
  - buildkite-agent
configuration:
  properties:
    env:
      type: string
    variables:
      type: object
    retry-max-attempts:
      type: number
      default: 5
    retry-base-delay:
      type: number
      default: 2
additionalProperties: false
