steps:
  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: secrets

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**

  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.1.1:
          folders:
            - tests
