#!/bin/bash
set -euo pipefail

# This hook only runs if the hook parameter is set to "pre-command".
if [[ "${BUILDKITE_PLUGIN_SECRETS_HOOK:-}" == "pre-command" ]]; then
  echo "Running in the pre-command hook"
else
  echo "Skipping pre-command hook"
  exit 0
fi

PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# shellcheck source=../lib/plugin.bash
if [[ -f "${PLUGIN_DIR}/lib/plugin.bash" ]]; then
  # shellcheck disable=SC1091
  source "${PLUGIN_DIR}/lib/plugin.bash"
else
  echo "[ERROR]: Failed to locate plugin library at ${PLUGIN_DIR}/lib/plugin.bash" >&2 # Can't use log_error yet
  exit 1
fi

run_secrets_fetch
